{% set version = "0.3.0" %}

package:
  name: sat-search
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sat-search/sat-search-{{ version }}.tar.gz
  sha256: bf59e96ae679bcddf4897a32d6f0e727a7b9a1b7443153681ee05fdecafc0245

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - sat-search=satsearch.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - sat-stac >=0.4.0,<0.5
    - pytest-runner
  run:
    - python >={{ python_min }}
    - sat-stac >=0.4.0,<0.5

test:
  imports:
    - satsearch
  commands:
    - pip check
    - sat-search --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sat-utils/sat-search
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python client for sat-api

extra:
  recipe-maintainers:
    - ocefpaf
