travis:
  secure:
    BINSTAR_TOKEN: sJ2hCBoJ+M181YoDMJ5fwVVh7N3w/8QSxf7tMiuExPEZBxoQWAj5E4XaumCPCeBELsELsr6xLPw8xLjhsfVg0TK5OhoYee6jmJrO6zENpaxDGIOhkDf+ti9XQmaSFxv+LSbpJH2i6HOoUMC4Ejpt0tNJsLl9rn8z3qg0/BMYsnF+6Zyf3FhYSifI9gV8P5s4cKq5lM3jq8eZFk2zVYAoydE+JBWXHVcSvZgBHv3qDC9zZGNWtCWFwTXGdLLzYyIkCbE2/9RZ5/6axyDnhaS2xzY20v6ZoN0beu9mTE/dCGy3eF+tinFx37jy9PrsN3jvqyB+an60D+qPUCYMjnKv2SwX0XeOgxhExtRxayYW3l4y2jdzr7IgrnO+hIwjTq2erayPclEFwiwW8if+PYjxmyG3iRZZO9kYVMghXUWHpc2mQgliHfhGFK/oFqzx6ePzmOL3vn6dODHzfvdaf08mjtCuFL6pBRfIUIw7lHqLTn4yZ3oOlesldte/7d1UJBEnL/sk85fJOZ784xTiH7bYQW5fK+BIhSbstUXlA5mQfKlqgDrXOx+mOF5RRmK6s5daMXIa5eC5VxAQA254obFJwUJbI7/Pd8zydju6591d/LfqUQUxwHgijbO2m21PDgxCxkS72nNmg5tSfLcwSjwSdH2XSnOsw2RZxzB7vO0z+GI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
